"""
Minimal Metropolis-Hastings sampling routines for the VMC tutorials.
"""

from __future__ import annotations

import jax
import jax.numpy as jnp
from functools import partial

__all__ = [
    "random_state",
    "sample_mcmc",
]


def random_state(key, n_chains, n_sites, dtype=jnp.int8):
    """Generate random spin configurations sigma_i in {-1, +1}."""
    bits = jax.random.bernoulli(key, p=0.5, shape=(n_chains, n_sites))
    return (2 * bits - 1).astype(dtype)


@partial(jax.jit, static_argnames=("logpsi", "n_samples_per_chain"))
def sample_mcmc(key, logpsi, params, sigma, n_samples_per_chain):
    """
    Run several single-spin-flip Metropolis-Hastings chains in parallel.

    Parameters
    ----------
    key
        JAX random key.
    logpsi
        Vectorised log-wavefunction, with signature logpsi(params, samples).
    params
        Wavefunction parameters.
    sigma
        Initial chain states, with shape (n_chains, n_sites).
    n_samples_per_chain
        Number of samples generated by each chain.

    Returns
    -------
    samples
        Array with shape (n_samples_per_chain, n_chains, n_sites).
    accepts
        Boolean array with shape (n_samples_per_chain, n_chains).
    sigma
        Final chain states, with shape (n_chains, n_sites).
    """

    def step(carry, _):
        key, sigma = carry

        key, key_site, key_accept = jax.random.split(key, 3)

        n_chains, n_sites = sigma.shape

        sites = jax.random.randint(
            key_site,
            shape=(n_chains,),
            minval=0,
            maxval=n_sites,
        )

        rows = jnp.arange(n_chains)
        sigma_proposed = sigma.at[rows, sites].multiply(-1)

        logp_ratio = 2.0 * (
            logpsi(params, sigma_proposed)
            - logpsi(params, sigma)
        )

        accept = (
            jnp.log(jax.random.uniform(key_accept, shape=(n_chains,)))
            < logp_ratio
        )

        sigma = jnp.where(accept[:, None], sigma_proposed, sigma)

        return (key, sigma), (sigma, accept)

    (_, sigma), (samples, accepts) = jax.lax.scan(
        step,
        init=(key, sigma),
        xs=None,
        length=n_samples_per_chain,
    )

    return samples, accepts, sigma
